/*************************************************************************/
/*                                                                       */
/*                  Language Technologies Institute                      */
/*                     Carnegie Mellon University                        */
/*                         Copyright (c) 2008                            */
/*                        All Rights Reserved.                           */
/*                                                                       */
/*  Permission is hereby granted, free of charge, to use and distribute  */
/*  this software and its documentation without restriction, including   */
/*  without limitation the rights to use, copy, modify, merge, publish,  */
/*  distribute, sublicense, and/or sell copies of this work, and to      */
/*  permit persons to whom this work is furnished to do so, subject to   */
/*  the following conditions:                                            */
/*   1. The code must retain the above copyright notice, this list of    */
/*      conditions and the following disclaimer.                         */
/*   2. Any modifications must be clearly marked as such.                */
/*   3. Original authors' names are not deleted.                         */
/*   4. The authors' names are not used to endorse or promote products   */
/*      derived from this software without specific prior written        */
/*      permission.                                                      */
/*                                                                       */
/*  CARNEGIE MELLON UNIVERSITY AND THE CONTRIBUTORS TO THIS WORK         */
/*  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING      */
/*  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT   */
/*  SHALL CARNEGIE MELLON UNIVERSITY NOR THE CONTRIBUTORS BE LIABLE      */
/*  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    */
/*  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN   */
/*  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,          */
/*  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF       */
/*  THIS SOFTWARE.                                                       */
/*                                                                       */
/*************************************************************************/
/*             Author:  Alan W Black (awb@cs.cmu.edu)                    */
/*               Date:  May 2008                                         */
/*************************************************************************/
/*                                                                       */
/*  To avoid an initialization phase where regexes need to be set up we  */
/*  precompile them into statics that can be used directly --            */
/*  (dhd championed this technique, and this is a reimplementation of    */
/*  his compilation technique this)                                      */
/*                                                                       */
/*************************************************************************/

#include "cst_regex.h"
#include <stdio.h>

static void regex_to_C(const char *name, const cst_regex *rgx, FILE* fp)
{
    int i;

    fprintf(fp, "static const unsigned char %s_rxprog[] = {\n   ", name);
    for (i = 0; i < rgx->regsize; i++)
    {
        fprintf(fp, "%d, ", (unsigned char) rgx->program[i]);
        if (i % 16 == 15)
            fprintf(fp, "\n   ");
    }
    fprintf(fp, "\n};\n\n");
    fprintf(fp, "static const cst_regex %s_rx = {\n   ", name);
    fprintf(fp, "%d, ", rgx->regstart);
    fprintf(fp, "%d, ", rgx->reganch);
    if (rgx->regmust == NULL)
        fprintf(fp, "NULL, ");
    else
        fprintf(fp, "%s_rxprog + %ld, ", name,
               (long int) (rgx->regmust - rgx->program));
    fprintf(fp, "%d, ", rgx->regmlen);
    fprintf(fp, "%d,\n   ", rgx->regsize);
    fprintf(fp, "(char *) %s_rxprog\n", name);
    fprintf(fp, "};\n\n");

    fprintf(fp, "const cst_regex *const %s = &%s_rx;\n\n", name, name);
}


int main(int argc, char **argv)
{
    size_t i;
    cst_regex *rgx;
    FILE *fp = fopen(argv[1], "wb");
    if (fp == NULL)
    {
        fprintf(stderr, "Could not open file %s\n", argv[1]);
        return -1;
    }
    fprintf(fp, "/* Autogenerated from compile_regexes2 */\n");
    const char *name_regex[][2] = {{"cst_rx_white", "[ \n\t\r]+"},
                                   {"cst_rx_alpha", "[A-Za-z]+"},
                                   {"cst_rx_uppercase", "[A-Z]+"},
                                   {"cst_rx_lowercase", "[a-z]+"},
                                   {"cst_rx_alphanum", "[0-9A-Za-z]+"},
                                   {"cst_rx_identifier", "[A-Za-z_][0-9A-Za-z_]+"},
                                   {"cst_rx_int", "-?[0-9]+"},
                                   {"cst_rx_double", "-?\\(\\([0-9]+\\.[0-9]*\\)\\|\\([0-9]+\\)\\|\\(\\.[0-9]+\\)\\)\\([eE][---+]?[0-9]+\\)?"},
                                   {"cst_rx_commaint", "[0-9][0-9]?[0-9]?,\\([0-9][0-9][0-9],\\)*[0-9][0-9][0-9]\\(\\.[0-9]+\\)?"},
                                   {"cst_rx_digits", "[0-9][0-9]*"},
                                   {"cst_rx_dotted_abbrev", "\\([A-Za-z]\\.\\)*[A-Za-z]"},
                                   {NULL, NULL}};
    for (i = 0; name_regex[i][0] != NULL; ++i)
    {
      rgx = new_cst_regex(name_regex[i][1]);
      regex_to_C(name_regex[i][0], rgx, fp);
      delete_cst_regex(rgx);
    }
    fclose(fp);
    return 0;
}

